# Generated by Django 3.2 on 2024-01-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_rename_ingredients_recipe_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(related_name='recipe', through='recipe.RecipeIngredient', to='recipe.Product'),
        ),
    ]
